server:
  port: 8081
  servlet:
    context-path: /demo-bi


  # HTTP 编码
  http:
    encoding:
      # 默认情况下，默认参数分别为UTF-8、true和 false
      charset: UTF-8
      enabled: true
      force: true

  # 国际化
  messages:
    basename: i18n/messages
    encoding: UTF-8

spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.15.22.9:3306/abke_oa?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    # 连接池
    hikari:
      pool-name: hikariCP
      maximum-pool-size: 25
      minimum-idle: 5

# MyBatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.abke.bi.domain
  global-config:
    # 驼峰下划线转换
    db-column-underline: true


enable:
  swagger: true
